channels:
  - conda-forge
  - defaults

dependencies:
  - pythonocc-core
  - fenics
  - pint
  - intervaltree
  - matplotlib
  - pyyaml
  - git
  - spyder
  - palettable
  - openmdao
  - mshr
  - pytest
  - pre-commit
  - pip
  - pip:
    - shapely
    - triangle

variables:
  PIP_EXTRA_INDEX_URL: https://pypi.org/simple
