channels:
  - conda-forge
  - defaults

dependencies:
  - fenics
  - git
  - intervaltree
  - matplotlib
  - mshr
  - openmdao
  - palettable
  - pint
  - pip
  - pytest
  - pythonocc-core
  - pyyaml
  - pre-commit
  - spyder
  - pip:
    - shapely
    - triangle
    - windIO

variables:
  PIP_EXTRA_INDEX_URL: https://pypi.org/simple
